name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bash .github/scripts/ci_install_deps.sh

      - name: Build (Debug)
        run: bash .github/scripts/ci_build.sh Debug

      - name: Test (Debug)
        run: bash .github/scripts/ci_test.sh Debug

      - name: Build (Release)
        run: bash .github/scripts/ci_build.sh Release

      - name: Test (Release)
        run: bash .github/scripts/ci_test.sh Release